name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: lts/*

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Lint Solidity and TypeScript code
        run: yarn run lint

      - name: Test the contracts and run code coverage
        run: yarn run coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
